# Generated by Django 2.1 on 2018-08-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20180828_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=255),
        ),
    ]
