# Generated by Django 2.1 on 2018-08-28 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_exam_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='exam',
        ),
        migrations.AddField(
            model_name='records',
            name='exam',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='teachers.Exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='teachers.Student'),
        ),
    ]
