# Generated by Django 2.1 on 2018-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20180828_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('high_score', models.PositiveIntegerField(unique=True)),
                ('low_score', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
