# Generated by Django 2.1 on 2018-08-29 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_points', models.PositiveIntegerField(unique=True)),
                ('low_points', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name_plural': 'Grades'},
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='minimum_subjects',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='records',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='grade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subject_records', to='teachers.Grades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='compulsory',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterUniqueTogether(
            name='teacherroles',
            unique_together={('subject', 'class_name')},
        ),
        migrations.AddField(
            model_name='points',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teachers.Grades'),
        ),
    ]
