# Generated by Django 2.1 on 2018-08-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20180830_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='points',
            field=models.PositiveIntegerField(),
        ),
    ]
