# Generated by Django 2.1 on 2018-08-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_auto_20180830_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='points',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
