# Generated by Django 2.1 on 2018-08-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_auto_20180830_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overallgrade',
            options={'verbose_name_plural': 'Overall Grades'},
        ),
        migrations.AlterField(
            model_name='overallgrade',
            name='high_points',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='overallgrade',
            name='low_points',
            field=models.IntegerField(unique=True),
        ),
    ]
