# Generated by Django 2.1 on 2018-08-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_auto_20180830_0316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('exam', 'student', 'subject')},
        ),
    ]
